###
POST http://localhost:8080/demand/create
Content-Type: application/json
//{"createData": {"title": "Test Demand", "avatar": "icon://ok", "description": "Some Test Demand"}}
//{"type": "MpRequestDemandCreate","createData": {"lastName": "Petrov", "firstName": "Alexandr", "contactPhone": "+79213245777","email": "a.sav210@gmail.com"}}

{"type": "MpRequestDemandCreate", "requestId":"1234","onResponse":"12312",
  "createData": {
    "lastName": "Petrov",
    "firstName": "Alexandr",
    "contactPhone": "+79213245777",
    "email": "a.sav210@gmail.com",
    "products": [{"idProduct": "Offer1","quantity":"1" },{"idProduct": "Offer2","quantity":"2" }]
  }
}


###
POST http://localhost:8080/demand/read
Content-Type: application/json

{
  "type": "MpRequestDemandRead",
  "demandId": "",
  "requestId": "req1"
}

###
POST http://localhost:8080/demand/update
Content-Type: application/json

//{"updateData": {"id": "d-rrt", "title": "Test Demand", "avatar": "icon://ok", "description": "Some Test Demand"}}
{"type": "MpRequestDemandUpdate", "requestId":"1234","onResponse":"12312",
  "updateData": {
    "lastName": "Petrov",
    "firstName": "Alexandr",
    "contactPhone": "+79213245777",
    "email": "a.sav210@gmail.com",
    "products": [{"idProduct": "Offer1","quantity":"1" },{"idProduct": "Offer2","quantity":"2" }],
    "id":"999"
  }
}
###
POST http://localhost:8080/demand/delete
Content-Type: application/json

{"type":"MpRequestDemandDelete", "demandId": "123"}
###
POST http://localhost:8080/phones/list
Content-Type: application/json

{"type": "MpRequestOffersList"}


###
